title: Ke Li (李珂)
logo: /assets/img/DCIM.jpg
description: Senior Researcher @Tencent Youtu Lab
show_contact_info: true
contact_info:
  scholar: https://scholar.google.com/citations?user=mfWsFM0AAAAJ&hl=en
  github: https://github.com/ieted
google_analytics: G-45M6MBPF31
theme: jekyll-theme-minimal
#color-scheme: auto-default-dark
